### ISSUE TITLE
test fails, not a git repo

### ISSUE THREAD

**Issue by colindaven** [weberlab-hhu/Predmoter#3]
Hi,
I have installed the tool into a container and am trying to run from Nextflow.

Error:
  fatal: not a git repository (or any of the parent directories): .git

It appears the Predmoter should not be a git repo, as it was installed by pip as recommended under manual installation (to /usr/local/bin. Or should I run the tool via hard-coding the full path to Predmoter.py in a cloned git repo in the container  ?

This is just a test, I'm not really planning to run it on organelles btw.

Thanks,
Colin

`    File "/usr/local/bin/Predmoter.py", line 13, in <module>`

`  Predmoter.py -f MA_organelles1.fasta -o MA_organelles1_predmoter.bw -m predict --model path/models/BiHybrid_04_predmoter_v0.3.2.ckpt -b 10 -of bigwig --species  --prefix MA_organelles1`

```
Command exit status:
  1

Command output:
  (empty)

Command error:
  fatal: not a git repository (or any of the parent directories): .git
  Traceback (most recent call last):
    File "/usr/local/bin/Predmoter.py", line 13, in <module>
      from predmoter.core.constants import PREDMOTER_VERSION, GIT_COMMIT
    File "/usr/local/lib/python3.8/dist-packages/predmoter/core/constants.py", line 5, in <module>
      GIT_COMMIT = subprocess.check_output(["git", "rev-parse", "--short", "HEAD"],
    File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/usr/lib/python3.8/subprocess.py", line 516, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['git', 'rev-parse', '--short', 'HEAD']' returned non-zero exit status 128.

```

**Comment by colindaven** [comment]
To solve my own problem, this code should help sort the problem (here with nextflow vars):
```

git config --global --add safe.directory /home/helixer_user/Predmoter    
python3 /home/helixer_user/Predmoter/Predmoter.py -f $fasta -of bw -m predict --model $params.model -b 120 -of bigwig --species $params.species --prefix $prefix
```
